# FROM maven:3.9.6-eclipse-temurin-21 AS build
#
# WORKDIR /app
#
# COPY pom.xml .
# COPY src ./src
#
# RUN mvn clean package
#
#
# FROM eclipse-temurin:21-jre
#
# WORKDIR /app
#
# COPY --from=build /app/target/*.jar /app/app.jar
#
# EXPOSE 8080
# ENTRYPOINT ["java", "-jar", "app.jar"]

FROM eclipse-temurin:21-jre-alpine

ENV BASE_DIR="/app"
ENV SERVICE_NAME="er-service"

WORKDIR /$BASE_DIR

COPY /target/*.jar /$BASE_DIR/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]